spring:
  profiles:
    include: oauth

  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/security
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #format_sql: true
        #show_sql: true

# JPA Log
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

